defaults:
  - tokenizer_training_config_schema
  
  - tokenizer: bpe_tokenizer

  - override hydra/job_logging: custom
  - override hydra/hydra_logging: disabled
  
  - _self_

hydra:
  output_subdir: null
  run:
    dir: .

data_parquet_path: gs://abhideep/cybulde/data/processed/filtered_data/train.parquet
text_column_name: cleaned_text