version: v3
data_local_save_dir: ./data/raw
dvc_remote_repo: https://github.com/venugudavalli/cybulde-data.git
dvc_data_folder: data/raw
github_user_name: venugudavalli
github_access_token_secret_id: cybulde-data-gh-access-token
infrastructure:
  project_id: cybulde-435213
  zone: europe-west2-b
  network: default
dataset_reader_manager:
  _target_: cybulde.data_processing.dataset_readers.DatasetReaderManager
  dataset_readers:
    ghc:
      _target_: cybulde.data_processing.dataset_readers.GHCDatasetReader
      dataset_dir: ./data/raw/ghc
      dataset_name: ghc
      gcp_project_id: cybulde-435213
      gcp_github_access_token_secret_id: cybulde-data-gh-access-token
      dvc_remote_repo: https://github.com/venugudavalli/cybulde-data.git
      github_user_name: venugudavalli
      version: v3
      dev_split_ratio: 0.3
    jtc:
      _target_: cybulde.data_processing.dataset_readers.JigsawToxicCommentsDatasetReader
      dataset_dir: ./data/raw/jigsaw-toxic-comment
      dataset_name: jtc
      gcp_project_id: cybulde-435213
      gcp_github_access_token_secret_id: cybulde-data-gh-access-token
      dvc_remote_repo: https://github.com/venugudavalli/cybulde-data.git
      github_user_name: venugudavalli
      version: v3
      dev_split_ratio: 0.03
    twt:
      _target_: cybulde.data_processing.dataset_readers.TwitterCommentsDatasetReader
      dataset_dir: ./data/raw/twitter
      dataset_name: twt
      gcp_project_id: cybulde-435213
      gcp_github_access_token_secret_id: cybulde-data-gh-access-token
      dvc_remote_repo: https://github.com/venugudavalli/cybulde-data.git
      github_user_name: venugudavalli
      version: v3
      dev_split_ratio: 0.125
      test_split_ratio: 0.1
  repartition: true
  available_memory: null
dataset_cleaner_manager:
  _target_: cybulde.data_processing.dataset_cleaners.DatasetCleanerManager
  dataset_cleaners:
    stop_words:
      _target_: cybulde.data_processing.dataset_cleaners.StopWordsDatasetCleaner
    to_lower_case:
      _target_: cybulde.data_processing.dataset_cleaners.ToLowerCaseDatasetCleaner
    url:
      _target_: cybulde.data_processing.dataset_cleaners.URLDatasetCleaner
    punctuation:
      _target_: cybulde.data_processing.dataset_cleaners.PunctuationDatasetCleaner
      punctuation: '!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~'
    non_letters:
      _target_: cybulde.data_processing.dataset_cleaners.NonLettersDatasetCleaner
    new_line:
      _target_: cybulde.data_processing.dataset_cleaners.NewLineCharacterDatasetCleaner
    non_ascii:
      _target_: cybulde.data_processing.dataset_cleaners.NonASCIIDatasetCleaner
    reference:
      _target_: cybulde.data_processing.dataset_cleaners.ReferenceToAccountDatasetCleaner
    re_tweet:
      _target_: cybulde.data_processing.dataset_cleaners.ReTweetDatasetCleaner
dask_cluster:
  _target_: dask.distributed.LocalCluster
  n_workers: 8
  memory_limit: auto
  processes: true
  threads_per_worker: 1
  scheduler_port: 8786
  silence_logs: 30
  host: null
  dashboard_address: :8787
  asynchronous: false
  blocked_handlers: null
  service_kwargs: null
  security: null
  protocol: null
  interface: null
  worker_class: null
processed_data_save_dir: gs://abhideep/cybulde/data/processed/filtered_data
run_tag: filtered_data
docker_image_name: europe-west2-docker.pkg.dev/cybulde-435213/cybulde/cybulde-data-processing
docker_image_tag: 4bdd1c14-5797-42cd-b4a1-d472260442a7
min_nrof_words: 2
