infrastructure:
  project_id: cybulde-435213
  zone: europe-west2-b
  network: default
data_parquet_path: gs://abhideep/cybulde/data/processed/filtered_data/train.parquet
text_column_name: cleaned_text
tokenizer:
  _target_: cybulde.tokenization.tokenizers.HuggingFaceTokenizer
  pre_tokenizer:
    _target_: tokenizers.pre_tokenizers.Whitespace
  model:
    _target_: tokenizers.models.BPE
    vocab: null
    merges: null
    cache_capacity: 10000
    dropout: null
    unk_token: '[UNK]'
    fuse_unk: false
  trainer:
    _target_: tokenizers.trainers.BpeTrainer
    vocab_size: 30000
    show_progress: true
    min_frequency: 0
    special_tokens:
    - '[UNK]'
    - '[CLS]'
    - '[SEP]'
    - '[PAD]'
    - '[MASK]'
    initial_alphabet: []
  normalizer: null
  decoder: null
  post_processor: null
  unk_token: '[UNK]'
  cls_token: '[CLS]'
  sep_token: '[SEP]'
  pad_token: '[PAD]'
  mask_token: '[MASK]'
docker_image_name: europe-west2-docker.pkg.dev/cybulde-435213/cybulde/cybulde-data-processing
docker_image_tag: bcde06b2-2b15-41b2-9479-891e2a7f1c2f
